services:
  - type: web
    name: nagarik-connect
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGODB_USERNAME
        sync: false
      - key: MONGODB_PASSWORD
        sync: false
      - key: MONGODB_CLUSTER
        sync: false
      - key: MONGODB_DATABASE
        value: icgs_complaints
      - key: SECRET_KEY
        generateValue: true
